# SSH endpoints
SSH_LOGIN=uab020077@alogin1.bsc.es
SSH_TRANSFER=uab020077@transfer1.bsc.es

# Remote project/data paths
REMOTE_ROOT=/gpfs/projects/uab103/uab020077/transformer_arch/transformer_arch_1/transformer_arch
REMOTE_DATA_ROOT=/gpfs/projects/uab103/uab020077/data/processed_data/tba

# Paths relative to repository root
LOCAL_EXPERIMENT_CONFIG=scripts/configs/neural_ae_experiment.toml
REMOTE_EXPERIMENT_CONFIG=scripts/BSC/generated_remote_config.toml
REMOTE_SBATCH_SCRIPT=scripts/BSC/run_neural_ae_remote.sh
