[data]
data_root_path = "/gpfs/projects/uab103/uab020077/data/processed_data/tba"
dataset_id = "2025-07-04_04_ESPM154_vol_000_subset_2048_target_random_order"
batch_size = 8
val_split = 0.1
shuffle_train = true
num_workers = 16
pin_memory = true
drop_last = false

[custom_model]
target = "v1tovideo.neural_autoencoder.models:TAE_v1"
input_dim = 64
latent_dim = 64
latent_num_tokens = 2048
num_layers = 4
nhead = 4

[train]
epochs = 260
learning_rate = 3e-05
lr_start = 3e-06
weight_decay = 0.0001
grad_clip_norm = 1.0
device = "cuda:0"

[train.loss]
name = "combined"
weight_id = 0.1
weight_time = 20.0
weight_rec = 10.0
name_id = "cross_entropy"
name_time = "masked_mae"
name_rec = "masked_mse"
poisson_log_input = true
poisson_full = false
poisson_eps = 1e-08

[output]
dir = "/gpfs/projects/uab103/uab020077/transformer_arch/transformer_arch_1/transformer_arch/outputs/neural_autoencoder/default_run"
